// <auto-generated />
using System;
using EcommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416194541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceApi.Models.AdminUser", b =>
                {
                    b.Property<int>("AdminUser_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminUser_Id"));

                    b.Property<DateTime>("AdminUser_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminUser_Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AdminUser_IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("AdminUser_PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AdminUser_StoreAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdminUser_StoreLogo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdminUser_StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AdminUser_StorePhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AdminUser_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminUser_Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminUser_Id");

                    b.HasIndex("AdminUser_Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("EcommerceApi.Models.Category", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_Id"));

                    b.Property<DateTime>("Category_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category_Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Category_DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Category_ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Category_IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category_Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Category_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Category_Id");

                    b.HasIndex("Category_Name")
                        .IsUnique();

                    b.HasIndex("Category_Slug")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EcommerceApi.Models.Order", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_Id"));

                    b.Property<string>("Order_AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order_AdminUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Order_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Order_Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Order_CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Order_CustomerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Order_CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Order_CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Order_Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Order_PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Order_PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Order_ShippingFeeLBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Order_ShippingFeeUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Order_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Order_SubtotalLBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Order_SubtotalUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Order_TotalAmountLBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Order_TotalAmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Order_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Order_Id");

                    b.HasIndex("Order_AdminUserId");

                    b.HasIndex("Order_Number")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcommerceApi.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItem_Id"));

                    b.Property<int>("OrderItem_OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderItem_ProductId")
                        .HasColumnType("int");

                    b.Property<string>("OrderItem_ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderItem_ProductSKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderItem_Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("OrderItem_TotalPriceLBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OrderItem_TotalPriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OrderItem_UnitPriceLBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OrderItem_UnitPriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItem_Id");

                    b.HasIndex("OrderItem_OrderId");

                    b.HasIndex("OrderItem_ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EcommerceApi.Models.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_Id"));

                    b.Property<int>("Product_AdminUserId")
                        .HasColumnType("int");

                    b.Property<int?>("Product_CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Product_CompareAtPriceLBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Product_CompareAtPriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Product_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Product_IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Product_IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Product_PriceLBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Product_PriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product_SKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Product_ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Product_Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("Product_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Product_Id");

                    b.HasIndex("Product_AdminUserId");

                    b.HasIndex("Product_CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EcommerceApi.Models.ProductImage", b =>
                {
                    b.Property<int>("ProductImage_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImage_Id"));

                    b.Property<DateTime>("ProductImage_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductImage_DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage_ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ProductImage_IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductImage_ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImage_Id");

                    b.HasIndex("ProductImage_ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("EcommerceApi.Models.Order", b =>
                {
                    b.HasOne("EcommerceApi.Models.AdminUser", "AdminUser")
                        .WithMany("Orders")
                        .HasForeignKey("Order_AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("EcommerceApi.Models.OrderItem", b =>
                {
                    b.HasOne("EcommerceApi.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderItem_OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderItem_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceApi.Models.Product", b =>
                {
                    b.HasOne("EcommerceApi.Models.AdminUser", "AdminUser")
                        .WithMany("Products")
                        .HasForeignKey("Product_AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Product_CategoryId");

                    b.Navigation("AdminUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EcommerceApi.Models.ProductImage", b =>
                {
                    b.HasOne("EcommerceApi.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductImage_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceApi.Models.AdminUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcommerceApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcommerceApi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EcommerceApi.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
